# Generated by Django 5.2 on 2025-04-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount_alter_refund_amount'),
        ('payments', '0005_vnd_currency_update'),
    ]

    operations = [
    ]
