# Generated by Django 5.2 on 2025-04-14 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='helpful votes'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_votes',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.ManyToManyField(blank=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
