# Generated by Django 5.2 on 2025-04-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_is_active_faq_product'),
        ('reviews', '0002_review_helpful_count_remove_review_helpful_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='products.product'),
        ),
    ]
