# Generated by Django 5.2 on 2025-04-13 08:16

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0003_faq_alter_product_developer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "đơn hàng",
                "verbose_name_plural": "đơn hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "sản phẩm trong đơn hàng",
                "verbose_name_plural": "sản phẩm trong đơn hàng",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_phone",
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày hoàn thành"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Ngày tạo"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                default="sepay", max_length=50, verbose_name="Phương thức thanh toán"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ thanh toán"),
                    ("completed", "Đã thanh toán"),
                    ("failed", "Thanh toán thất bại"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ thanh toán"),
                    ("completed", "Đã thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Tổng tiền",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Mã giao dịch",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="download_url",
            field=models.URLField(blank=True, verbose_name="URL tải xuống"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="license_key",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="License key",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Giá",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Số lượng",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="orders_orde_user_id_0886b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="orders_orde_order_i_52f79a_idx"
            ),
        ),
    ]
