# Generated by Django 5.2 on 2025-04-13 08:22

from django.db import migrations, models
import uuid

def fix_transaction_ids(apps, schema_editor):
    # Get the Order model
    Order = apps.get_model('orders', 'Order')
    db_alias = schema_editor.connection.alias
    
    # Fix empty transaction_ids to prevent UNIQUE constraint violations
    # Set a unique uuid for each order with empty transaction_id
    orders = Order.objects.using(db_alias).all()
    for order in orders:
        if not order.transaction_id or order.transaction_id == '':
            order.transaction_id = f"MIGRATION-{uuid.uuid4().hex}"
            order.save()

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_transaction_ids),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Địa chỉ giao hàng"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email giao hàng"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Số điện thoại giao hàng",
            ),
        ),
    ]
