# Generated by Django 5.2 on 2025-04-11 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_icons/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "software_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop Application"),
                            ("web", "Web Application"),
                            ("mobile", "Mobile Application"),
                            ("plugin", "Plugin/Extension"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="software type",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("single", "Single User"),
                            ("multi", "Multi User"),
                            ("enterprise", "Enterprise"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=20,
                        verbose_name="license type",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="version")),
                (
                    "system_requirements",
                    models.TextField(blank=True, verbose_name="system requirements"),
                ),
                (
                    "supported_platforms",
                    models.CharField(
                        max_length=255, verbose_name="supported platforms"
                    ),
                ),
                (
                    "file_size",
                    models.CharField(max_length=50, verbose_name="file size"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="products/thumbnails/", verbose_name="thumbnail"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="download count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("release_date", models.DateField(verbose_name="release date")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/screenshots/", verbose_name="screenshot"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product screenshot",
                "verbose_name_plural": "product screenshots",
                "ordering": ["order"],
            },
        ),
    ]
