# Generated by Django 5.2 on 2025-04-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="demo_url",
            field=models.URLField(blank=True, null=True, verbose_name="demo URL"),
        ),
        migrations.AddField(
            model_name="product",
            name="download_url",
            field=models.URLField(blank=True, null=True, verbose_name="download URL"),
        ),
    ]
