# Generated by Django 5.2 on 2025-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_total_amount_alter_orderitem_price_and_more'),
        ('products', '0005_vnd_currency_update'),
    ]

    operations = [
    ]
